### ISSUE TITLE
Add Linter

### ISSUE THREAD

**Issue by SKAUL05** [BITSoC/livestream#5]
Create Github Actions for following Linter

- [x] Python
- [x] JavaScript

**Comment by iamrajiv** [comment]
@SKAUL05 I want to work on this issue.

**Comment by SKAUL05** [comment]
@iamrajiv Which Linting are u thinking to include for both the languages.

**Comment by iamrajiv** [comment]
@SKAUL05 My suggestion would be `Flake8` for Python & `ESLint` for JavaScript.

**Comment by SKAUL05** [comment]
Okay go ahead with ESLint for JavaScript, but try to implement psf/black for Python along with Flake8.

**Comment by SKAUL05** [comment]
@iamrajiv Reopening Issue. Tasks Failing #7

**Comment by iamrajiv** [comment]
@SKAUL05 I will try to implement what you have suggested in #7. Also, I think only Black is failing because I have just updated #9 and ESLint is passing and Black is failing.

**Comment by SKAUL05** [comment]
> @SKAUL05 I will try to implement what you have suggested in #7. Also, I think only Black is failing because I have just updated #9 and ESLint is passing and Black is failing.

Yeah update Black accordingly. I will update #9 once this issue gets resolved and all test cases pass.

**Comment by SKAUL05** [comment]
Check, there are two separate files Eslint & Lint. Both r running same code. Pls look into it and flake8 is not running in #9

**Comment by iamrajiv** [comment]
Sure, I will go through it. @SKAUL05
